### ISSUE TITLE
安装后重启打不开

### ISSUE THREAD

**Issue by apples1949** [zilewang7/LiteLoaderQQNT-Esc-Shortcut-Key#1]
![image](https://github.com/user-attachments/assets/e98dce8f-615e-4f1d-bf24-a7806c70879d)
 已确认，plugin中删除LiteLoaderQQNT-Esc-Shortcut-Key就正常
已安装插件列表
![image](https://github.com/user-attachments/assets/c1d23683-d2c3-4753-9f42-5bace1b21bcc)
![image](https://github.com/user-attachments/assets/61acc4e8-eb67-4906-921e-64c40fe4c53b)

**Comment by zilewang7** [comment]
因为这个插件我是做来在 mac 上用的，没有在 windows 上测试过，后面我兼容一下

**Comment by apples1949** [comment]
> 因为这个插件我是做来在 mac 上用的，没有在 windows 上测试过，后面我兼容一下

好的

**Comment by zilewang7** [comment]
现在支持 Windows 了

**Comment by apples1949** [comment]
![image](https://github.com/user-attachments/assets/75623cc5-2733-4186-994c-f3147f605018)

**Comment by apples1949** [comment]
测试不了，触发风控了

**Comment by zilewang7** [comment]
> 测试不了，触发风控了

没理解，是哪里的问题

**Comment by apples1949** [comment]
![66c236ea5eaf7e045edeab94bd07bc5a](https://github.com/user-attachments/assets/b14d5e98-9c5f-4cae-a423-87b7c35738d8)
![0b236dcc3a1d25ff11d735119a75b5a2_720](https://github.com/user-attachments/assets/e73fa227-c139-4920-9a6f-603e8d8f8d77)

**Comment by zilewang7** [comment]
好吧
